

-- ----------------------------
-- Table structure for houses_v1
-- ----------------------------
DROP TABLE IF EXISTS "public"."houses_v1";
CREATE TABLE "public"."houses_v1" (
  "id" varchar(255) COLLATE "pg_catalog"."default",
  "House_name" varchar(255) COLLATE "pg_catalog"."default",
  "Region" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of houses_v1
-- ----------------------------
INSERT INTO "public"."houses_v1" VALUES ('1', 'Algood', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('2', 'Allyrion of Godsgrace', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('3', 'Amber', 'North');
INSERT INTO "public"."houses_v1" VALUES ('4', 'Ambrose', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('5', 'Andrik of Southshield', 'Iron Islands (Shield Islands)');
INSERT INTO "public"."houses_v1" VALUES ('6', 'Appleton of Appleton', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('7', 'Arryn of Gulltown', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('8', 'Arryn of the Eyrie', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('9', 'Ashford of Ashford', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('10', 'Ashwood', 'North');
INSERT INTO "public"."houses_v1" VALUES ('11', 'Baelish of Harrenhal', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('12', 'Baelish of the Fingers', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('13', 'Ball', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('14', 'Banefort of Banefort', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('15', 'Bar Emmon of Sharp Point', 'Crownlands (Dragonstone)');
INSERT INTO "public"."houses_v1" VALUES ('16', 'Baratheon of Dragonstone', 'Crownlands (Dragonstone)');
INSERT INTO "public"."houses_v1" VALUES ('17', 'Baratheon of King''s Landing', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('18', 'Baratheon of Storm''s End', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('19', 'Beesbury of Honeyholt', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('20', 'Belgrave', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('21', 'Belmore of Strongsong', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('22', 'Bettley', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('23', 'Bigglestone', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('24', 'Blackbar of Bandallon', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('25', 'Blackberry', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('26', 'Blackfyre', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('27', 'Blackmont of Blackmont', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('28', 'Blackmyre', 'North (Crannogmen)');
INSERT INTO "public"."houses_v1" VALUES ('29', 'Blacktyde of Blacktyde', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('30', 'Blackwood of Raventree Hall', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('31', 'Blanetree', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('32', 'Blount', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('33', 'Boggs', 'Crownlands (Crackclaw Point)');
INSERT INTO "public"."houses_v1" VALUES ('34', 'Boggs', 'North (Crannogmen)');
INSERT INTO "public"."houses_v1" VALUES ('35', 'Bole', 'North (Wolfswood Clans)');
INSERT INTO "public"."houses_v1" VALUES ('36', 'Bolling', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('37', 'Bolton of the Dreadfort', 'North');
INSERT INTO "public"."houses_v1" VALUES ('38', 'Bolton of Winterfell', 'North');
INSERT INTO "public"."houses_v1" VALUES ('39', 'Borrell of Sweetsister', 'Vale of Arryn (Sistermen)');
INSERT INTO "public"."houses_v1" VALUES ('40', 'Botley of Lordsport', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('41', 'Bracken of Stone Hedge', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('42', 'Branch', 'North (Wolfswood Clans)');
INSERT INTO "public"."houses_v1" VALUES ('43', 'Brax of Hornvale', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('44', 'Breakstone', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('45', 'Briar', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('46', 'Bridges', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('47', 'Brightstone', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('48', 'Brook', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('49', 'Broom', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('50', 'Brownhill', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('51', 'Brune of Brownhollow', 'Crownlands (Crackclaw Point)');
INSERT INTO "public"."houses_v1" VALUES ('52', 'Brune of the Dyre Den', 'Crownlands (Crackclaw Point)');
INSERT INTO "public"."houses_v1" VALUES ('53', 'Buckler of Bronzegate', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('54', 'Buckwell of the Antlers', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('55', 'Bulwer of Blackcrown', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('56', 'Burley', 'North (Mountain Clans)');
INSERT INTO "public"."houses_v1" VALUES ('57', 'Bushy', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('58', 'Butterwell of Whitewalls', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('59', 'Byrch', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('60', 'Bywater', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('61', 'Cafferen of Fawnton', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('62', 'Cargyll', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('63', 'Caron of Nightsong', 'Stormlands (Marcher Lords)');
INSERT INTO "public"."houses_v1" VALUES ('64', 'Cassel', 'North');
INSERT INTO "public"."houses_v1" VALUES ('65', 'Casterly of Casterly Rock', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('66', 'Caswell of Bitterbridge', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('67', 'Cave', 'Crownlands (Crackclaw Point)');
INSERT INTO "public"."houses_v1" VALUES ('68', 'Celtigar of Claw Isle', 'Crownlands (Dragonstone)');
INSERT INTO "public"."houses_v1" VALUES ('69', 'Cerwyn of Castle Cerwyn', 'North');
INSERT INTO "public"."houses_v1" VALUES ('70', 'Chambers', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('71', 'Charlton', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('72', 'Chelsted', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('73', 'Chester of Greenshield', 'Reach (Shield Islands)');
INSERT INTO "public"."houses_v1" VALUES ('74', 'Chyttering', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('75', 'Clegane of Clegane''s Keep', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('76', 'Clifton', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('77', 'Cobb', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('78', 'Cockshaw', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('79', 'Codd', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('80', 'Coldwater of Coldwater Burn', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('81', 'Cole', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('82', 'Condon', 'North');
INSERT INTO "public"."houses_v1" VALUES ('83', 'Conklyn', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('84', 'Connington of Griffin''s Roost', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('85', 'Corbray of Heart''s Home', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('86', 'Cordwayner of Hammerhal', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('87', 'Costayne of the Three Towers', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('88', 'Cox of Saltpans', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('89', 'Crabb of the Whispers', 'Crownlands (Crackclaw Point)');
INSERT INTO "public"."houses_v1" VALUES ('90', 'Crakehall of Crakehall', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('91', 'Crane of Red Lake', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('92', 'Cray', 'North (Crannogmen)');
INSERT INTO "public"."houses_v1" VALUES ('93', 'Cressey', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('94', 'Crowl of Deepdown', 'North (Skagosi Clans)');
INSERT INTO "public"."houses_v1" VALUES ('95', 'Cupps', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('96', 'Cuy of Sunhouse', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('97', 'Dalt of Lemonwood', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('98', 'Dargood', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('99', 'Darke', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('100', 'Darklyn of Duskendale', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('101', 'Darkwood', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('102', 'Darry of Darry', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('103', 'Dayne of High Hermitage', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('104', 'Dayne of Starfall', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('105', 'Deddings', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('106', 'Doggett', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('107', 'Dondarrion of Blackhaven', 'Stormlands (Marcher Lords)');
INSERT INTO "public"."houses_v1" VALUES ('108', 'Donniger', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('109', 'Drinkwater', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('110', 'Drox', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('111', 'Drumm of Old Wyk', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('112', 'Dryland of Hellgate Hall', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('113', 'Dunn', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('114', 'Durrandon', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('115', 'Durwell', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('116', 'Dustin of Barrowton', 'North');
INSERT INTO "public"."houses_v1" VALUES ('117', 'Edgerton', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('118', 'Egen', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('119', 'Elesham of the Paps', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('120', 'Erenford', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('121', 'Errol of Haystack Hall', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('122', 'Estermont of Greenstone', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('123', 'Estren of Wyndhall', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('124', 'Falwell', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('125', 'Farman of Faircastle', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('126', 'Farring', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('127', 'Farrow', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('128', 'Farwynd of Sealskin Point', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('129', 'Farwynd of the Lonely Light', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('130', 'Fell of Felwood', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('131', 'Fenn', 'North (Crannogmen)');
INSERT INTO "public"."houses_v1" VALUES ('132', 'Ferren', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('133', 'Fisher of the Misty Isle', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('134', 'Fisher of the Stony Shore', 'North');
INSERT INTO "public"."houses_v1" VALUES ('135', 'Flint of Breakstone Hill', 'North');
INSERT INTO "public"."houses_v1" VALUES ('136', 'Flint of Flint''s Finger', 'North');
INSERT INTO "public"."houses_v1" VALUES ('137', 'Flint of the mountains', 'North (Mountain Clans)');
INSERT INTO "public"."houses_v1" VALUES ('138', 'Flint of Widow''s Watch', 'North');
INSERT INTO "public"."houses_v1" VALUES ('139', 'Florent of Brightwater Keep', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('140', 'Follard', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('141', 'Foote', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('142', 'Foote of Nightsong', 'Stormlands (Marcher Lords)');
INSERT INTO "public"."houses_v1" VALUES ('143', 'Footly of Tumbleton', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('144', 'Forrester', 'North (Wolfswood Clans)');
INSERT INTO "public"."houses_v1" VALUES ('145', 'Fossoway of Cider Hall', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('146', 'Fossoway of New Barrel', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('147', 'Fowler of Skyreach', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('148', 'Frey of Riverrun', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('149', 'Frey of the Crossing', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('150', 'Frost', 'North');
INSERT INTO "public"."houses_v1" VALUES ('151', 'Gardener of Highgarden', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('152', 'Gargalen of Salt Shore', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('153', 'Garner', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('154', 'Gaunt', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('155', 'Glover of Deepwood Motte', 'North');
INSERT INTO "public"."houses_v1" VALUES ('156', 'Goodbrook', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('157', 'Goodbrother of Corpse Lake', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('158', 'Goodbrother of Crow Spike Keep', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('159', 'Goodbrother of Downdelving', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('160', 'Goodbrother of Orkmont', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('161', 'Goodbrother of Shatterstone', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('162', 'Goodbrother of Hammerhorn', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('163', 'Goode', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('164', 'Gower', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('165', 'Graceford of Holyhall', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('166', 'Grafton of Gulltown', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('167', 'Grandison of Grandview', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('168', 'Graves', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('169', 'Greenfield of Greenfield', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('170', 'Greengood', 'North (Crannogmen)');
INSERT INTO "public"."houses_v1" VALUES ('171', 'Greenhill', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('172', 'Greenwood', 'North');
INSERT INTO "public"."houses_v1" VALUES ('173', 'Grell', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('174', 'Grey', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('175', 'Greyiron of Orkmont', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('176', 'Greyjoy of Pyke', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('177', 'Greystark of the Wolf''s Den', 'North');
INSERT INTO "public"."houses_v1" VALUES ('178', 'Grimm of Greyshield', 'Reach (Shield Islands)');
INSERT INTO "public"."houses_v1" VALUES ('179', 'Groves', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('180', 'Haigh', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('181', 'Hamell', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('182', 'Harclay', 'North (Mountain Clans)');
INSERT INTO "public"."houses_v1" VALUES ('183', 'Hardy', 'Crownlands (Crackclaw Point)');
INSERT INTO "public"."houses_v1" VALUES ('184', 'Hardyng', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('185', 'Harlaw of Grey Garden', 'Iron Islands (Shield Islands)');
INSERT INTO "public"."houses_v1" VALUES ('186', 'Harlaw of Harlaw Hall', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('187', 'Harlaw of Harridan Hill', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('188', 'Harlaw of Harlaw', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('189', 'Harlaw of the Tower of Glimmering', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('190', 'Harroway of Harrenhal', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('191', 'Harte', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('192', 'Hastwyck', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('193', 'Hasty', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('194', 'Hawick of Saltpans', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('195', 'Hawthorne', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('196', 'Hayford of Hayford', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('197', 'Heddle', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('198', 'Herston', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('199', 'Hersy of Newkeep', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('200', 'Hetherspoon', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('201', 'Hewett of Oakenshield', 'Reach (Shield Islands)');
INSERT INTO "public"."houses_v1" VALUES ('202', 'Hightower of the Hightower', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('203', 'Hoare of Orkmont', 'Iron Islands (origin)');
INSERT INTO "public"."houses_v1" VALUES ('204', 'Hogg of Sow''s Horn', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('205', 'Hollard', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('206', 'Holt', 'North');
INSERT INTO "public"."houses_v1" VALUES ('207', 'Holt', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('208', 'Hook', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('209', 'Hornwood of Hornwood', 'North');
INSERT INTO "public"."houses_v1" VALUES ('210', 'Horpe', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('211', 'Hull', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('212', 'Humble', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('213', 'Hunt', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('214', 'Hunter of Longbow Hall', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('215', 'Hutcheson', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('216', 'Inchfield', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('217', 'Ironmaker', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('218', 'Ironsmith', 'North');
INSERT INTO "public"."houses_v1" VALUES ('219', 'Jast', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('220', 'Jordayne of the Tor', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('221', 'Justman', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('222', 'Karstark of Karhold', 'North');
INSERT INTO "public"."houses_v1" VALUES ('223', 'Keath', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('224', 'Kellington', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('225', 'Kenning of Harlaw', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('226', 'Kenning of Kayce', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('227', 'Kettleblack', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('228', 'Kidwell of Ivy Hall', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('229', 'Knott', 'North (Mountain Clans)');
INSERT INTO "public"."houses_v1" VALUES ('230', 'Kyndall', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('231', 'Ladybright', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('232', 'Lake', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('233', 'Lake', 'North');
INSERT INTO "public"."houses_v1" VALUES ('234', 'Langward', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('235', 'Lannett', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('236', 'Lannister of Casterly Rock', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('237', 'Lannister of Darry', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('238', 'Lannister of Lannisport', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('239', 'Lanny', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('240', 'Lantell', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('241', 'Leek', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('242', 'Lefford of the Golden Tooth', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('243', 'Leygood', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('244', 'Liddle', 'North (Mountain Clans)');
INSERT INTO "public"."houses_v1" VALUES ('245', 'Lightfoot', 'North');
INSERT INTO "public"."houses_v1" VALUES ('246', 'Lipps', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('247', 'Locke of Oldcastle', 'North');
INSERT INTO "public"."houses_v1" VALUES ('248', 'Lolliston', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('249', 'Long', 'North');
INSERT INTO "public"."houses_v1" VALUES ('250', 'Longthorpe of Longsister', 'Vale of Arryn (Sistermen)');
INSERT INTO "public"."houses_v1" VALUES ('251', 'Longwaters', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('252', 'Lonmouth', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('253', 'Lorch', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('254', 'Lothston of Harrenhal', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('255', 'Lowther', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('256', 'Lyberr', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('257', 'Lychester', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('258', 'Lydden of Deep Den', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('259', 'Lynderly of Snakewood', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('260', 'Magnar of Kingshouse', 'North (Skagosi Clans)');
INSERT INTO "public"."houses_v1" VALUES ('261', 'Mallery', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('262', 'Mallister of Seagard', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('263', 'Manderly of White Harbor', 'North');
INSERT INTO "public"."houses_v1" VALUES ('264', 'Mandrake', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('265', 'Manning', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('266', 'Manwoody of Kingsgrave', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('267', 'Marbrand of Ashemark', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('268', 'Marsh', 'North');
INSERT INTO "public"."houses_v1" VALUES ('269', 'Martell of Sunspear', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('270', 'Massey of Stonedance', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('271', 'Meadows of Grassy Vale', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('272', 'Melcolm of Old Anchor', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('273', 'Merlyn of Pebbleton', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('274', 'Merryweather of Longtable', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('275', 'Mertyns of Mistwood', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('276', 'Middlebury', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('277', 'Mollen', 'North');
INSERT INTO "public"."houses_v1" VALUES ('278', 'Moore', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('279', 'Mooton of Maidenpool', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('280', 'Moreland', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('281', 'Mormont of Bear Island', 'North');
INSERT INTO "public"."houses_v1" VALUES ('282', 'Morrigen of Crow''s Nest', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('283', 'Moss', 'North');
INSERT INTO "public"."houses_v1" VALUES ('284', 'Mudd of Oldstones', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('285', 'Mullendore of Uplands', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('286', 'Musgood', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('287', 'Myatt', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('288', 'Myre of Harlaw', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('289', 'Nayland of Hag''s Mire', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('290', 'Netley', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('291', 'Norcross', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('292', 'Norrey', 'North (Mountain Clans)');
INSERT INTO "public"."houses_v1" VALUES ('293', 'Norridge', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('294', 'Nute of Oakenshield', 'Iron Islands (Shield Islands)');
INSERT INTO "public"."houses_v1" VALUES ('295', 'Nutt', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('296', 'Oakheart of Old Oak', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('297', 'Oldflowers', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('298', 'Orkwood of Orkmont', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('299', 'Orme', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('300', 'Osgrey of Leafy Lake', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('301', 'Osgrey of Standfast', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('302', 'Overton', 'North');
INSERT INTO "public"."houses_v1" VALUES ('303', 'Paege', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('304', 'Parren', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('305', 'Payne', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('306', 'Peake of Starpike', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('307', 'Peasebury of Poddingfield', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('308', 'Peat', 'North (Crannogmen)');
INSERT INTO "public"."houses_v1" VALUES ('309', 'Peckledon', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('310', 'Pemford', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('311', 'Penny', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('312', 'Penrose of Parchments', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('313', 'Perryn', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('314', 'Piper of Pinkmaiden', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('315', 'Plumm', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('316', 'Pommingham', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('317', 'Poole', 'North');
INSERT INTO "public"."houses_v1" VALUES ('318', 'Potter', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('319', 'Prester of Feastfires', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('320', 'Pryor of Pebble', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('321', 'Pyle', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('322', 'Pyne', 'Crownlands (Crackclaw Point)');
INSERT INTO "public"."houses_v1" VALUES ('323', 'Qoherys of Harrenhal', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('324', 'Qorgyle of Sandstone', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('325', 'Quagg', 'North (Crannogmen)');
INSERT INTO "public"."houses_v1" VALUES ('326', 'Rambton', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('327', 'Redbeard', 'North');
INSERT INTO "public"."houses_v1" VALUES ('328', 'Redding', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('329', 'Redfort of Redfort', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('330', 'Redwyne of the Arbor', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('331', 'Reed of Greywater Watch', 'North (Crannogmen)');
INSERT INTO "public"."houses_v1" VALUES ('332', 'Reyne of Castamere', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('333', 'Rhysling', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('334', 'Risley of Risley Glade', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('335', 'Rogers of Amberly', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('336', 'Rollingford', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('337', 'Roote of Lord Harroway''s Town', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('338', 'Rosby of Rosby', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('339', 'Rowan of Goldengrove', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('340', 'Roxton of the Ring', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('341', 'Royce of Runestone', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('342', 'Royce of the Gates of the Moon', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('343', 'Ruskyn', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('344', 'Ruthermont', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('345', 'Ruttiger', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('346', 'Ryder of the Rills', 'North');
INSERT INTO "public"."houses_v1" VALUES ('347', 'Ryger of Willow Wood', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('348', 'Rykker of Duskendale', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('349', 'Ryswell of the Rills', 'North');
INSERT INTO "public"."houses_v1" VALUES ('350', 'Saltcliffe of Saltcliffe', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('351', 'Santagar of Spottswood', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('352', 'Sarsfield of Sarsfield', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('353', 'Sawyer', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('354', 'Seaworth of Cape Wrath', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('355', 'Selmy of Harvest Hall', 'Stormlands (Marcher Lords)');
INSERT INTO "public"."houses_v1" VALUES ('356', 'Serrett of Silverhill', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('357', 'Serry of Southshield', 'Reach (Shield Islands)');
INSERT INTO "public"."houses_v1" VALUES ('358', 'Sharp', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('359', 'Shawney', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('360', 'Shell', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('361', 'Shell', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('362', 'Shepherd', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('363', 'Shermer of Smithyton', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('364', 'Shett of Gull Tower', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('365', 'Shett of Gulltown', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('366', 'Slate of Blackpool', 'North');
INSERT INTO "public"."houses_v1" VALUES ('367', 'Sloane', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('368', 'Slynt of Harrenhal', 'Crownlands (origin)');
INSERT INTO "public"."houses_v1" VALUES ('369', 'Smallwood of Acorn Hall', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('370', 'Sparr of Great Wyk', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('371', 'Spicer of Castamere', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('372', 'Stackhouse', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('373', 'Stackspear', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('374', 'Staedmon of Broad Arch', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('375', 'Stane of Driftwood Hall', 'North (Skagosi Clans)');
INSERT INTO "public"."houses_v1" VALUES ('376', 'Stark of Winterfell', 'North');
INSERT INTO "public"."houses_v1" VALUES ('377', 'Staunton of Rook''s Rest', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('378', 'Stokeworth of Stokeworth', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('379', 'Stonehouse of Old Wyk', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('380', 'Stonetree of Harlaw', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('381', 'Stout of Goldgrass', 'North');
INSERT INTO "public"."houses_v1" VALUES ('382', 'Strickland', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('383', 'Strong of Harrenhal', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('384', 'Suggs', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('385', 'Sunderland of the Three Sisters', 'Vale of Arryn (Sistermen)');
INSERT INTO "public"."houses_v1" VALUES ('386', 'Sunderly of Saltcliffe', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('387', 'Sunglass of Sweetport Sound', 'Crownlands (Dragonstone)');
INSERT INTO "public"."houses_v1" VALUES ('388', 'Swann of Stonehelm', 'Stormlands (Marcher Lords)');
INSERT INTO "public"."houses_v1" VALUES ('389', 'Swyft of Cornfield', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('390', 'Swygert', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('391', 'Tallhart of Torrhen''s Square', 'North');
INSERT INTO "public"."houses_v1" VALUES ('392', 'Tarbeck of Tarbeck Hall', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('393', 'Targaryen of King''s Landing', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('394', 'Tarly of Horn Hill', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('395', 'Tarth of Evenfall Hall', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('396', 'Tawney of Orkmont', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('397', 'Teague', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('398', 'Templeton of Ninestars', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('399', 'Terrick', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('400', 'Thenn', 'North');
INSERT INTO "public"."houses_v1" VALUES ('401', 'Thorne', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('402', 'Toland of Ghost Hill', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('403', 'Tollett of the Grey Glen', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('404', 'Torrent of Littlesister', 'Vale of Arryn (Sistermen)');
INSERT INTO "public"."houses_v1" VALUES ('405', 'Towers', 'North');
INSERT INTO "public"."houses_v1" VALUES ('406', 'Towers of Harrenhal', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('407', 'Toyne', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('408', 'Trant of Gallowsgrey', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('409', 'Tudbury', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('410', 'Tully of Riverrun', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('411', 'Turnberry', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('412', 'Tyrell of Brightwater Keep', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('413', 'Tyrell of Highgarden', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('414', 'Uffering', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('415', 'Uller of the Hellholt', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('416', 'Umber of the Last Hearth', 'North');
INSERT INTO "public"."houses_v1" VALUES ('417', 'Upcliff of the Witch Isle', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('418', 'Vaith of the Red Dunes', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('419', 'Vance of Atranta', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('420', 'Vance of Wayfarer''s Rest', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('421', 'Varner', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('422', 'Velaryon of Driftmark', 'Crownlands (Dragonstone)');
INSERT INTO "public"."houses_v1" VALUES ('423', 'Vikary', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('424', 'Volmark of Volmark', 'Iron Islands (Shield Islands)');
INSERT INTO "public"."houses_v1" VALUES ('425', 'Vypren', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('426', 'Vyrwel of Darkdell', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('427', 'Wade', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('428', 'Wagstaff', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('429', 'Warrick', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('430', 'Waterman', 'North');
INSERT INTO "public"."houses_v1" VALUES ('431', 'Waxley of Wickenden', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('432', 'Wayn', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('433', 'Waynwood of Ironoaks', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('434', 'Weatherwax', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('435', 'Weaver', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('436', 'Webber of Coldmoat', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('437', 'Wells', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('438', 'Wells', 'North');
INSERT INTO "public"."houses_v1" VALUES ('439', 'Wendwater', 'Crownlands');
INSERT INTO "public"."houses_v1" VALUES ('440', 'Wensington', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('441', 'Westbrook', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('442', 'Westerling of the Crag', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('443', 'Whitfield', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('444', 'Whent of Harrenhal', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('445', 'Whitehead of the Weeping Town', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('446', 'Whitehill of Highpoint', 'North');
INSERT INTO "public"."houses_v1" VALUES ('447', 'Willum', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('448', 'Wode', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('449', 'Woodfoot of Bear Island', 'North');
INSERT INTO "public"."houses_v1" VALUES ('450', 'Woodhull', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('451', 'Woods', 'North (Wolfswood Clans)');
INSERT INTO "public"."houses_v1" VALUES ('452', 'Woodwright', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('453', 'Woolfield', 'North');
INSERT INTO "public"."houses_v1" VALUES ('454', 'Wull', 'North (Mountain Clans)');
INSERT INTO "public"."houses_v1" VALUES ('455', 'Wydman', 'Vale of Arryn');
INSERT INTO "public"."houses_v1" VALUES ('456', 'Wyl of the Boneway', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('457', 'Wylde of Rain House', 'Stormlands');
INSERT INTO "public"."houses_v1" VALUES ('458', 'Wynch of Iron Holt', 'Iron Islands');
INSERT INTO "public"."houses_v1" VALUES ('459', 'Wythers', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('460', 'Yarwyck', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('461', 'Yelshire', 'Reach');
INSERT INTO "public"."houses_v1" VALUES ('462', 'Yew', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('463', 'Yronwood of Yronwood', 'Dorne');
INSERT INTO "public"."houses_v1" VALUES ('464', 'Branfield', 'Unknown');
INSERT INTO "public"."houses_v1" VALUES ('465', 'Forrester of Ironrath', 'North (Wolfswood Clans)');
INSERT INTO "public"."houses_v1" VALUES ('466', 'Glenmore of Rillwater Crossing', 'North');
INSERT INTO "public"."houses_v1" VALUES ('467', 'Tuttle', 'North');
INSERT INTO "public"."houses_v1" VALUES ('468', 'Whitehill', 'North');
INSERT INTO "public"."houses_v1" VALUES ('469', 'Harlton of Castlewood', 'Riverlands');
INSERT INTO "public"."houses_v1" VALUES ('470', 'Sarwyck of Riverspring', 'Westerlands');
INSERT INTO "public"."houses_v1" VALUES ('471', 'Westford', 'Westerlands');
